environment:
  matrix:
  - nodejs_version: ''
  - nodejs_version: 7
  - nodejs_version: 6
  - nodejs_version: 4

install:
  - ps: if ($env:nodejs_version -like '') { Install-Product node $env:nodejs_version }
  - npm i -g npm@3
  - npm install
  - set CI=true

test_script:
  - node --version
  - npm --version
  - ps: if ($env:nodejs_version -like '') { npm run lint }
  - "node bin/cli.js || ver > null"
  - "echo Exit code: %errorlevel%"

build: off
shallow_clone: true
clone_depth: 1
version: '{build}'
matrix:
  fast_finish: true
